// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TurnosMedicos.Infrastructure.Data;

#nullable disable

namespace TurnosMedicos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("TurnosMedicos.Domain.Models.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SucursalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Especialidad = "Clínica Médica",
                            NombreCompleto = "Dr. Alejandro Ríos",
                            SucursalId = 1
                        },
                        new
                        {
                            Id = 2,
                            Especialidad = "Pediatría",
                            NombreCompleto = "Dra. Valentina Mora",
                            SucursalId = 1
                        },
                        new
                        {
                            Id = 3,
                            Especialidad = "Cardiología",
                            NombreCompleto = "Dr. Carlos Benítez",
                            SucursalId = 2
                        },
                        new
                        {
                            Id = 4,
                            Especialidad = "Dermatología",
                            NombreCompleto = "Dra. Lucía Ferraro",
                            SucursalId = 2
                        },
                        new
                        {
                            Id = 5,
                            Especialidad = "Traumatología",
                            NombreCompleto = "Dr. Martín Gutiérrez",
                            SucursalId = 3
                        });
                });

            modelBuilder.Entity("TurnosMedicos.Domain.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaBloqueo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoShowCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bloqueado = false,
                            CreatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DNI = "28445123",
                            Email = "gonzalo.herrera@gmail.com",
                            IsActive = true,
                            NoShowCount = 0,
                            NombreCompleto = "Gonzalo Herrera",
                            Telefono = "1145678901"
                        },
                        new
                        {
                            Id = 2,
                            Bloqueado = false,
                            CreatedAt = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DNI = "31202456",
                            Email = "mariana.lopez@hotmail.com",
                            IsActive = true,
                            NoShowCount = 0,
                            NombreCompleto = "Mariana López",
                            Telefono = "1167891234"
                        },
                        new
                        {
                            Id = 3,
                            Bloqueado = false,
                            CreatedAt = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DNI = "25789012",
                            Email = "roberto.q@gmail.com",
                            IsActive = true,
                            NoShowCount = 0,
                            NombreCompleto = "Roberto Quintana",
                            Telefono = "1156789012"
                        },
                        new
                        {
                            Id = 4,
                            Bloqueado = false,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DNI = "35123789",
                            Email = "sofia.vargas@yahoo.com",
                            IsActive = true,
                            NoShowCount = 0,
                            NombreCompleto = "Sofía Vargas",
                            Telefono = "1178901234"
                        },
                        new
                        {
                            Id = 5,
                            Bloqueado = false,
                            CreatedAt = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DNI = "29876543",
                            Email = "diegofernandez@gmail.com",
                            IsActive = true,
                            NoShowCount = 0,
                            NombreCompleto = "Diego Fernández",
                            Telefono = "1134567890"
                        },
                        new
                        {
                            Id = 6,
                            Bloqueado = false,
                            CreatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DNI = "33456789",
                            Email = "lauragimenez@gmail.com",
                            IsActive = true,
                            NoShowCount = 0,
                            NombreCompleto = "Laura Giménez",
                            Telefono = "1189012345"
                        },
                        new
                        {
                            Id = 7,
                            Bloqueado = true,
                            CreatedAt = new DateTime(2025, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DNI = "27345678",
                            Email = "facundo.sosa@outlook.com",
                            FechaBloqueo = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            NoShowCount = 0,
                            NombreCompleto = "Facundo Sosa",
                            Telefono = "1112345678"
                        },
                        new
                        {
                            Id = 8,
                            Bloqueado = false,
                            CreatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DNI = "36901234",
                            Email = "carolina.mendez@gmail.com",
                            IsActive = true,
                            NoShowCount = 0,
                            NombreCompleto = "Carolina Méndez",
                            Telefono = "1190123456"
                        });
                });

            modelBuilder.Entity("TurnosMedicos.Domain.Models.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sucursales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Av. Santa Fe 3500, CABA",
                            Nombre = "Palermo"
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Av. Cabildo 1200, CABA",
                            Nombre = "Belgrano"
                        },
                        new
                        {
                            Id = 3,
                            Direccion = "Defensa 850, CABA",
                            Nombre = "San Telmo"
                        });
                });

            modelBuilder.Entity("TurnosMedicos.Domain.Models.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("MedicoId", "FechaHora")
                        .IsUnique();

                    b.ToTable("Turnos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Pendiente",
                            FechaCreacion = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHora = new DateTime(2026, 5, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 1,
                            Motivo = "Control anual",
                            PacienteId = 1
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Confirmado",
                            FechaCreacion = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHora = new DateTime(2026, 4, 30, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 3,
                            Motivo = "Revisión cardiológica",
                            PacienteId = 2
                        },
                        new
                        {
                            Id = 3,
                            Estado = "NoShow",
                            FechaCreacion = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHora = new DateTime(2026, 3, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 2,
                            Motivo = "Pediatría seguimiento",
                            PacienteId = 2
                        },
                        new
                        {
                            Id = 4,
                            Estado = "NoShow",
                            FechaCreacion = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHora = new DateTime(2026, 2, 18, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 1,
                            Motivo = "Consulta general",
                            PacienteId = 2
                        },
                        new
                        {
                            Id = 5,
                            Estado = "Pendiente",
                            FechaCreacion = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHora = new DateTime(2026, 5, 12, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 4,
                            Motivo = "Revisión de piel",
                            PacienteId = 3
                        },
                        new
                        {
                            Id = 6,
                            Estado = "Confirmado",
                            FechaCreacion = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHora = new DateTime(2026, 5, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 5,
                            Motivo = "Dolor en rodilla derecha",
                            PacienteId = 4
                        },
                        new
                        {
                            Id = 7,
                            Estado = "Cancelado",
                            FechaCreacion = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHora = new DateTime(2026, 4, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 1,
                            Motivo = "Chequeo general",
                            PacienteId = 5
                        },
                        new
                        {
                            Id = 8,
                            Estado = "Pendiente",
                            FechaCreacion = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHora = new DateTime(2026, 5, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 2,
                            Motivo = "Control pediátrico",
                            PacienteId = 6
                        },
                        new
                        {
                            Id = 9,
                            Estado = "Atendido",
                            FechaCreacion = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHora = new DateTime(2026, 4, 4, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 3,
                            Motivo = "Electrocardiograma de rutina",
                            PacienteId = 1
                        },
                        new
                        {
                            Id = 10,
                            Estado = "Pendiente",
                            FechaCreacion = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHora = new DateTime(2026, 5, 3, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 4,
                            Motivo = "Primera consulta",
                            PacienteId = 8
                        });
                });

            modelBuilder.Entity("TurnosMedicos.Domain.Models.Medico", b =>
                {
                    b.HasOne("TurnosMedicos.Domain.Models.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("TurnosMedicos.Domain.Models.Turno", b =>
                {
                    b.HasOne("TurnosMedicos.Domain.Models.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurnosMedicos.Domain.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
